In [3]:
import pandas as pd
df = pd.read_csv(r"/home/hari/Documents/Data Scientist Workout/Day 5/framingham_heart_disease.csv")
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [ ]:
print(df['education'].isnull().sum())

KeyError: 'education'

In [5]:
df = df.drop(['education'], axis=1)
df.head()

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [6]:
df['cigsPerDay']=df['cigsPerDay'].fillna(df['cigsPerDay'].mean())
df.tail()

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [7]:
clg_mean=round(df['cigsPerDay'].mean())
clg_mean

9

In [8]:
df['cigsPerDay'].fillna(clg_mean, inplace=True)
df.tail()

/tmp/ipykernel_17070/78695744.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cigsPerDay'].fillna(clg_mean, inplace=True)

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [10]:
df['cigsPerDay'].isnull().sum()
df.tail()

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [11]:
x=df.drop('TenYearCHD', axis=1)
x

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0
4235,0,48,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0
4236,0,44,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0

In [12]:
from sklearn.model_selection import train_test_split
print(train_test_split(x, df['TenYearCHD'], test_size=0.3, random_state=42))

[      male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
2010     0   42              1         9.0     0.0                0
3340     0   64              0         0.0     1.0                0
3591     0   39              0         0.0     0.0                0
2742     1   40              1        20.0     0.0                0
4034     0   40              1        20.0     0.0                0
...    ...  ...            ...         ...     ...              ...
3444     0   36              1         5.0     0.0                0
466      0   57              1        15.0     0.0                0
3092     0   60              0         0.0     0.0                0
3772     1   39              1        10.0     0.0                0
860      0   35              0         0.0     0.0                0

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose
2010             1         0    274.0  135.0   90.0  22.19       70.0      NaN
3340             1         0    285.0  160.0   87.0  29.97       65.0     87.0
3591             0         0    205.0  104.0   74.0  20.55       68.0      NaN
2742             0         0    228.0  131.0   80.0  26.77       64.0     74.0
4034             0         0    213.0  130.0   80.0  19.98       96.0     76.0
...            ...       ...      ...    ...    ...    ...        ...      ...
3444             1         0    222.0  147.0   94.0  26.79       76.0     71.0
466              0         0    250.0  125.0   74.0  21.08       80.0     72.0
3092             1         0    298.0  133.0   89.0  25.09       83.0     81.0
3772             0         0    215.0  102.0   64.5  24.50       68.0     62.0
860              0         0    248.0  107.0   73.0  20.64       90.0     80.0

[2966 rows x 14 columns],       male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
3188     1   63              0         0.0     0.0                0
764      1   45              0         0.0     0.0                0
3264     0   51              1         2.0     0.0                0
1967     1   45              1        30.0     0.0                0
2185     0   45              1         3.0     0.0                0
...    ...  ...            ...         ...     ...              ...
610      1   55              1        15.0     0.0                0
570      0   49              1         3.0     0.0                0
343      1   43              1        25.0     0.0                0
2159     0   42              1        15.0     0.0                0
2357     0   42              0         0.0     0.0                0

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose
3188             1         0    190.0  148.0   90.0  27.13       72.0     86.0
764              0         0    162.0  125.0   89.0  27.98       85.0     83.0
3264             0         0    261.0  127.0   81.0  20.24       75.0     96.0
1967             0         0    250.0  126.0   89.5  28.68       75.0     92.0
2185             0         0    250.0  130.0   80.0  20.24       90.0     86.0
...            ...       ...      ...    ...    ...    ...        ...      ...
610              1         0    222.0  155.0   92.5  28.35       67.0     68.0
570              0         0    247.0  121.0   82.0  29.07       72.0     69.0
343              0         0    245.0  126.0   88.5  23.16       92.0      NaN
2159             0         0    212.0  115.0   72.0  23.72       73.0    100.0
2357             0         0    270.0  126.0   86.0  23.98       80.0     77.0

[1272 rows x 14 columns], 2010    0
3340    0
3591    0
2742    0
4034    0
       ..
3444    0
466     0
3092    0
3772    0
860     0
Name: TenYearCHD, Length: 2966, dtype: int64, 3188    0
764     0
3264    0
1967    0
2185    0
       ..
610     1
570     0
343     1
2159    0
2357    0
Name: TenYearCHD, Length: 1272, dtype: int64]

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000)
classifier.fit(x_train, y_train)

NameError: name 'x_train' is not defined